kind: Pod
apiVersion: v1
metadata:
  name: db-baseline
  labels:
    app: db-baseline
spec:
  restartPolicy: Never
  containers:
    - name: db-baseline
      image: db-baseline:latest
      imagePullPolicy: Never
      envFrom:
        - configMapRef:
            name: flyway-env
        - secretRef:
            name: flyway-secret
      command: ["flyway", "-locations=.", "baseline", "-baselineVersion=0"]