apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah-flyway
spec:
  description: build flyway image.
  params:
    - name: IMAGE
      description: Reference of the image buildah will produce.
      default: db-migration
    - name: STORAGE_DRIVER
      description: Set buildah storage driver
      default: vfs
    - name: DOCKERFILE
      description: Path to the Dockerfile to build.
      default: Dockerfile
    - name: version
      description: App version
      default: 0.9.1
    - name: registry_url
      description: Docker registry URL
      default: registry.kube-system.svc.cluster.local:5000
  workspaces:
    - name: source
  steps:
    - name: build
      image: quay.io/buildah/stable
      workingDir: $(workspaces.source.path)/infrastructure/src/main/resources/db-migration
      script: |
        buildah build \
          --storage-driver=vfs \
          --layers \
          --file Dockerfile \
          --tag $(params.IMAGE):$(params.version) \
          .
        
        buildah push \
          --tls-verify=false \
          --log-level=trace \
          --storage-driver=vfs \
          --digestfile $(workspaces.source.path)/image-digest \
          $(params.IMAGE):$(params.version) \
          10.244.0.4:5000/$(params.IMAGE):$(params.version)

      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
      securityContext:
        privileged: true
        capabilities:
          # needed by `buildah build`
          add: [ "SETFCAP" ]

  volumes:
    - name: varlibcontainers
      emptyDir: {}
