apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-application
spec:
  description: |
    This pipeline clones a git repo, then echoes the README file to the stout and them makes a custom build of the Flyway image
  params:
    - name: repo-url
      type: string
      description: The git repo URL to clone from.
  workspaces:
    - name: shared-data
      description: |
        This workspace contains the cloned repo files, so they can be read by the
        next task.
#    - name: git-credentials
#      description: My ssh credentials
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
#        - name: ssh-directory
#          workspace: git-credentials
      params:
        - name: url
          value: $(params.repo-url)
    - name: check-init-container-docker-file
      runAfter: ["fetch-source" ]
      taskRef:
        name: check-file-exists
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: FILE_PATH
          value: "infrastructure/src/main/resources/db-migration/Dockerfile"
    - name: build-flyway-image
      runAfter: [ "check-init-container-docker-file" ]
      when:
        - input: "$(tasks.check-init-container-docker-file.results.EXISTS)"
          operator: in
          values: ['true']
      taskRef:
        name: build-custom-image
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: DOCKERFILE_PATH
          value: infrastructure/src/main/resources/db-migration
    - name: build-spring-app
      runAfter: [ "build-flyway-image" ]
      taskRef:
        name: mvn-build
      workspaces:
        - name: source
          workspace: shared-data
      params:
          - name: is-springboot-app-launcher
            value: 'false'
    - name: repackage-spring-app
      runAfter: [ "build-spring-app" ]
      taskRef:
        name: mvn-build
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: is-springboot-app-launcher
          value: 'true'
        - name: PATH
          value: 'launcher'
    - name: check-app-docker-file
      runAfter: [ "repackage-spring-app" ]
      taskRef:
        name: check-file-exists
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: FILE_PATH
          value: "Dockerfile"
    - name: build-springboot-app-image
      runAfter: [ "check-app-docker-file" ]
      when:
        - input: "$(tasks.check-app-docker-file.results.EXISTS)"
          operator: in
          values: [ 'true' ]
      taskRef:
        name: build-custom-image
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: DOCKERFILE_PATH
          value: ''