apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: clone-build-run-
spec:
  pipelineRef:
    name: clone-build
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
#    - name: git-credentials
#      secret:
#        secretName: git-credentials
  params:
    - name: repo-url
      value: https://github.com/dmitrychebayewski/hexagonal-library.git