apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah-flyway
spec:
  description: build flyway image.
  params:
    - name: IMAGE
      description: Reference of the image buildah will produce.
      default: db-migration
    - name: STORAGE_DRIVER
      description: Set buildah storage driver
      default: vfs
    - name: DOCKERFILE
      description: Path to the Dockerfile to build.
      default: Dockerfile
    - name: version
      description: App version
      default: 0.9.1
  workspaces:
    - name: source
  steps:
    - name: build
      image: quay.io/buildah/stable
      workingDir: $(workspaces.source.path)/infrastructure/src/main/resources/db-migration
      script: |
        buildah build \
          --storage-driver=vfs
          --layers \
          --file Dockerfile \
          --tag $(params.IMAGE):$(params.version) \
          .

#        buildah --storage-driver=$(params.STORAGE_DRIVER) bud \
#          --no-cache -f $(params.DOCKERFILE) -t $(params.IMAGE) .
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
      securityContext:
        privileged: true
  volumes:
    - name: varlibcontainers
      emptyDir: {}
